const nowplaying = {
  dates: {
    maximum: "2023-10-20",
    minimum: "2023-09-02",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/mRGmNnh6pBAGGp6fMBMwI8iTBUO.jpg",
      genre_ids: [27, 9648, 53],
      id: 968051,
      original_language: "en",
      original_title: "The Nun II",
      overview:
        "1956년, 프랑스의 한 성당에서 신부가 끔찍하게 살해당한다. 이 사건을 조사하기 위해 파견된 아이린 수녀는 4년 전 자신을 공포에 떨게 했던 악마의 기운을 느낀다. 어두운 밤, 계속해서 일어나는 의문의 사건들 가운데 충격적인 진실이 드러나는데…",
      popularity: 2386.129,
      poster_path: "/hx4R7GqhiUP2LHJZJNrzCIqadd3.jpg",
      release_date: "2023-09-27",
      title: "더 넌 2",
      video: false,
      vote_average: 7,
      vote_count: 920,
    },
    {
      adult: false,
      backdrop_path: "/fwXeTKmJvlv7kbH8QDmbykGfMeK.jpg",
      genre_ids: [16, 10751, 28, 878],
      id: 893723,
      original_language: "en",
      original_title: "PAW Patrol: The Mighty Movie",
      overview:
        "신비한 힘을 가진 유성이 어드벤처 시티에 떨어진 날, 퍼피 구조대는 유성에서 나온 크리스탈 덕분에 초능력을 가진 ‘퍼피 히어로즈’로 변신한다. 하지만 악당 ‘험딩어 시장’과 미치광이 과학자 ‘빅토리아’는 초능력의 원천인 크리스탈을 빼앗아 어드벤처 시티를 지배하려 하는데..! 작고 약하게 태어났지만 오랫동안 큰 꿈을 키워 온 ‘스카이’와 퍼피 히어로즈는 주니어 구조대원들과 함께 어드벤처 시티를 지켜낼 수 있을까?",
      popularity: 1492.743,
      poster_path: "/62CEuwp287mbVarn3f2KcSAsrj1.jpg",
      release_date: "2023-10-06",
      title: "퍼피 구조대: 더 마이티 무비",
      video: false,
      vote_average: 7.7,
      vote_count: 41,
    },
    {
      adult: false,
      backdrop_path: "/r7DuyYJ0N3cD8bRKsR5Ygq2P7oa.jpg",
      genre_ids: [12, 28, 18],
      id: 980489,
      original_language: "en",
      original_title: "Gran Turismo",
      overview:
        "레이싱 게임 ‘그란 투리스모’의 덕후 ‘잔 마든보로’ 스피드라고는 게임으로만 만족해야 했던 그에게 레이싱 선수 발굴을 목표로 만들어진 ‘그란 투리스모 콘테스트’라는 기회가 찾아온다. 앉아서 게임만 하던 그의 앞에 닥친 혹독한 훈련과 치열한 경쟁.뛰어난 잠재력을 입증해 프로 레이싱 팀에 합류하는데 성공하지만 상대팀 선수들은 게이머 출신인 그를 인정하지 않고, 프로 레이싱의 세계는 그를 더욱 거칠게 몰아붙이는데...  리셋 버튼 없는 목숨을 건 실전! 게이머에서 레이서가 된 소년의 흥미로운 스토리가 스크린에서 펼쳐진다!",
      popularity: 1374.1,
      poster_path: "/mewjjhpju5JT1wDFJDMdctWcCqd.jpg",
      release_date: "2023-09-20",
      title: "그란 투리스모",
      video: false,
      vote_average: 8.1,
      vote_count: 1009,
    },
    {
      adult: false,
      backdrop_path: "/rMvPXy8PUjj1o8o1pzgQbdNCsvj.jpg",
      genre_ids: [28, 12, 53],
      id: 299054,
      original_language: "en",
      original_title: "Expend4bles",
      overview:
        "핵무기를 탈취한 무장 세력을 추격하는 익스펜더블 팀의 활약을 그린 액션 영화",
      popularity: 599.754,
      poster_path: "/y8L3N9KGGal2CiNgIJ5tP5W9iAF.jpg",
      release_date: "2023-10-18",
      title: "익스펜더블 4",
      video: false,
      vote_average: 6.3,
      vote_count: 148,
    },
    {
      adult: false,
      backdrop_path: "/f33XdT6dwNXmXQNvQ4FuyhQrUob.jpg",
      genre_ids: [27],
      id: 807172,
      original_language: "en",
      original_title: "The Exorcist: Believer",
      overview:
        "한날한시에 동시에 사라졌던 앤젤라와 캐서린.  기억이 전부 사라진 채 상처투성이 몸으로 돌아온 두 아이는  이상증세를 보이며 날이 갈수록 섬뜩하게 변해간다. 마침내 두 아이의 몸을 동시에 차지한 악마가 존재를 드러내고, 한 명을 살리면 한 명이 죽는다는 충격적인 사실이 밝혀지는데…",
      popularity: 579.61,
      poster_path: "/gekQTgjZkPhpglvP1ZdTHBwi7xO.jpg",
      release_date: "2023-10-18",
      title: "엑소시스트: 믿는 자",
      video: false,
      vote_average: 5.5,
      vote_count: 89,
    },
    {
      adult: false,
      backdrop_path: "/w2nFc2Rsm93PDkvjY4LTn17ePO0.jpg",
      genre_ids: [16, 35, 28],
      id: 614930,
      original_language: "en",
      original_title: "Teenage Mutant Ninja Turtles: Mutant Mayhem",
      overview:
        "뉴욕의 하수구로 스며든 미스터리한 녹색 액체, ‘우즈’로 인해 아기 거북이 네 마리와 청년 쥐 스플린터는 사람과 비슷한 모습의 돌연변이가 된다. 15년 후, 10대 청소년이 된 레오나르도, 미켈란젤로, 라파엘, 도나텔로는 하수구에 숨어 사는 생활에서 벗어나 인간 세상에서 평범한 삶을 살고 싶어하고 우연히 만난 학생 기자 에이프릴과 함께 도시를 위협하는 '슈퍼플라이'와 그 일당을 물리치면 뉴욕의 히어로가 되어 당당히 세상에 나갈 수 있을 거라는 꿈을 꾸는데… 인간들을 모두 돌연변이로 만들겠다는 ‘슈퍼플라이’의 음모로 위험에 빠진 뉴욕! 틴에이저 히어로로 다시 태어난 ‘닌자터틀’ 형제들의 스트릿 액션 어드벤처가 펼쳐진다!",
      popularity: 333.124,
      poster_path: "/6xORIhe6cP3iM5RYTHs7MTOH1qa.jpg",
      release_date: "2023-09-14",
      title: "닌자터틀: 뮤턴트 대소동",
      video: false,
      vote_average: 7.3,
      vote_count: 729,
    },
    {
      adult: false,
      backdrop_path: "/c6Splshb8lb2Q9OvUfhpqXl7uP0.jpg",
      genre_ids: [28, 53],
      id: 717930,
      original_language: "en",
      original_title: "Kandahar",
      overview:
        "CIA 비밀요원 ‘톰’(제라드 버틀러) 그는 이란의 핵 작전’을 무마시키기 위해 경유지인 아프가니스탄으로 향한다. 하지만 펜타곤 소속 내부 고발자로 인해 작전이 노출되고, 톰의 신분도 탄로나게 된다. 파키스탄 정보부와 이슬람 무장단체 탈레반은 톰을 납치하기 위해 움직이기 시작했고, 톰은 동맹군이 있는 칸다하로 향하게 되는데... 400마일 떨어진 아프가니스탄의 칸다하, 그곳만이 유일한 탈출구이다!",
      popularity: 367.357,
      poster_path: "/M2w3Hl3Xnjwjm06A14PuuRVOWe.jpg",
      release_date: "2023-09-20",
      title: "칸다하",
      video: false,
      vote_average: 6.9,
      vote_count: 628,
    },
    {
      adult: false,
      backdrop_path: "/iQcCAm8hKWZyUntqrvzyEGtXyJl.jpg",
      genre_ids: [878, 28, 53],
      id: 670292,
      original_language: "en",
      original_title: "The Creator",
      overview:
        "인류를 지키기 위해 만들어진 AI가 LA에 핵폭탄을 터뜨린 후, 인류와 AI 간의 피할 수 없는 전쟁이 시작된다. 전직 특수부대 요원 ‘조슈아’는 실종된 아내의 단서를 얻을지도 모른다는 생각에 전쟁을 끝내기 위한 인류의 작전에 합류한다. 인류를 위협할 강력한 무기와 이를 창조한 ‘창조자’를 찾아 나서고, 그 무기가 아이 모습의 AI 로봇 '알피'란 사실을 알게 되는데… 인간적인가, 인간의 적인가? 10월, SF 블록버스터의 신세계가 펼쳐진다!",
      popularity: 236.496,
      poster_path: "/vFsSluuzqxR46Ils9ib52ItdE9u.jpg",
      release_date: "2023-10-03",
      title: "크리에이터",
      video: false,
      vote_average: 7.2,
      vote_count: 358,
    },
    {
      adult: false,
      backdrop_path: "/vT17lPUglrAzjEqMwjPpIDe49ty.jpg",
      genre_ids: [16, 12, 10751, 14],
      id: 459003,
      original_language: "uk",
      original_title: "Мавка: Лісова пісня",
      overview:
        "오랜 전쟁의 끝, 서로의 문을 닫아 버린 마법의 숲과 인간 세상. 숲의 정령이자 대자연의 새로운 수호자, 마브카는 어느 날 순수한 마음을 지닌 인간 청년 루카스와 사랑에 빠진다. 하지만 악당 킬리나는 사랑에 빠진 마브카의 마음을 이용해 숲을 파괴하고 숲의 심장을 차지하려는 음모를 꾸미는데…",
      popularity: 242.692,
      poster_path: "/oYv6T3ADPgGZHN3CUsZtT4WNJtC.jpg",
      release_date: "2023-10-18",
      title: "마브카 : 숲의 노래",
      video: false,
      vote_average: 7.3,
      vote_count: 410,
    },
    {
      adult: false,
      backdrop_path: "/uvsL5Q5Juf8ivqBnlr4nFVUwVoa.jpg",
      genre_ids: [80, 18, 53],
      id: 466420,
      original_language: "en",
      original_title: "Killers of the Flower Moon",
      overview:
        "1920년대 오클라호마주 오세이지 부족 땅에서 석유가 발견된 후, 부족 사람들이 한 명씩 죽어 나가자 FBI가 미스터리를 풀기 위해 나선다.",
      popularity: 199.006,
      poster_path: "/zIKcqDlE69Q5LYOneGzXawpr9Ye.jpg",
      release_date: "2023-10-19",
      title: "플라워 킬링 문",
      video: false,
      vote_average: 10,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/qZOuoBoKCDLSm1EvYz2eBub8Cto.jpg",
      genre_ids: [16, 12, 14, 10751],
      id: 939338,
      original_language: "fr",
      original_title: "Pattie et la colère de Poséidon",
      overview:
        "평화로운 항구 도시의 꼬마 생쥐 ‘패티’는 전설 속 아르고 원정대처럼 위대한 모험을 하고 영웅이 되는 꿈을 꾼다. 하지만 겁 많은 딸 바라기 아빠 고양이 ‘샘’은 자꾸 위험한 바깥세상으로 나가려 하는 ‘패티’가 걱정스럽다. 어느 날, 질투 많은 바다의 신 ‘포세이돈’이 멋진 삼지창을 든 자신의 동상을 세우라 명령하고, ‘패티’는 위기에 처한 도시를 살리기 위해 전설의 아르고 원정대를 부활시켜 모험을 떠난다. 걱정 많은 ‘샘’도 어쩔 수 없이 모험에 동참하는데…",
      popularity: 187.343,
      poster_path: "/crgWtan0cslODPqfYe9X4hqeYhT.jpg",
      release_date: "2023-09-21",
      title: "아르고 원정대: 꼬마 영웅 패티의 대모험",
      video: false,
      vote_average: 7,
      vote_count: 44,
    },
    {
      adult: false,
      backdrop_path: "/8FhKnPpql374qyyHAkZDld93IUw.jpg",
      genre_ids: [9648, 53, 878],
      id: 536437,
      original_language: "en",
      original_title: "Hypnotic",
      overview:
        "과거 공원에 놀러갔다가 잠시 한눈을 판 사이에 어린 딸을 잃어버린 대니 루크 형사는 힘든 나날을 보내고 있다. 그러던 어느 날 시민의 신고로 출동한 은행 강도 사건에서 딸의 실종과 관련된 단서를 발견하는데...",
      popularity: 166.815,
      poster_path: "/bzn2BY0QWiClC2tOHWVAxp7FeCg.jpg",
      release_date: "2023-09-20",
      title: "힙노틱",
      video: false,
      vote_average: 6.4,
      vote_count: 648,
    },
    {
      adult: false,
      backdrop_path: "/2zzaJ9jzyK1Am8XoS0dFjmP8V0L.jpg",
      genre_ids: [28, 53, 27],
      id: 1135229,
      original_language: "en",
      original_title: "I Am Rage",
      overview:
        "에린은 새로운 남자친구의 고향인 어느 한적한 시골마을을 방문한다. 그곳에서 비슷하게 여행을 온 커플들을 만나게 되고 그들은 실종이 되어도 누구도 찾지 않은 외로운 사람들이라는 공통점이 있다는 것을 알게 된다. 그들은 인간의 피를 거래하고 마시며 초자연적인 힘을 얻는 사이비 살인마 집단에 납치된 것. 하지만 에린은 위기에 몰리거나 분노하게 되면 극한의 잔인함과 폭력성이 초인적으로 발현되는 특이한 혈통을 가진 체질이다. 에린의 분노가 폭발하고 그녀를 사냥한 악인들에 대한 더욱 잔혹한 사냥이 시작된다.",
      popularity: 142.33,
      poster_path: "/z1nFd03qoiCrHlGSxBlumkF9uZh.jpg",
      release_date: "2023-09-14",
      title: "론 서바이버 : 아이 엠 리벤지",
      video: false,
      vote_average: 6.7,
      vote_count: 19,
    },
    {
      adult: false,
      backdrop_path: "/nYDPmxvl0if5vHBBp7pDYGkTFc7.jpg",
      genre_ids: [27],
      id: 709631,
      original_language: "en",
      original_title: "Cobweb",
      overview:
        "이제 막 여덟 살이 된 소년 ‘피터’ . 밤이 찾아오면, 방에서 의문의 노크 소리가 들려왔고, 끔찍한 공포에 사로잡힌 피터는 부모님 ‘마크’와 ‘캐롤’에게 이 사실을 알린다..  하지만 그들이 피터의 방에 들어선 순간 아무런 소리도 들리지 않아 대수롭지 않게 여긴다. 다음 날 저녁, 피터는 또다시 방에서 의문의 노크 소리를 듣게 되고 소리가 나는 방향으로 한 발자국 씩 다가간다. 그리고 방 벽지를 뜯어보니 자그마한 구멍이 뚫려 있었고, 벽 너머로 정체를 알 수 없는 ‘무언가’의 목소리가 들려오는데…",
      popularity: 125.549,
      poster_path: "/5Ol63pZT8JfYgFMfADqySpgwkdj.jpg",
      release_date: "2023-09-20",
      title: "노크: 더 하우스",
      video: false,
      vote_average: 6.9,
      vote_count: 415,
    },
    {
      adult: false,
      backdrop_path: "/kHlX3oqdD4VGaLpB8O78M25KfdS.jpg",
      genre_ids: [9648, 53, 80],
      id: 945729,
      original_language: "en",
      original_title: "A Haunting in Venice",
      overview:
        "세계적 명탐정 에르큘 포와로는 오랜 탐정 생활에서 은퇴하여 아름다운 도시 베니스에서 평범한 삶을 살아가고 있다. 그런 그에게 오랜 친구이자 베스트셀러 작가인 아리아드네 올리버가 찾아와 죽은 영혼을 부를 수 있다고 알려진 영험한 심령술사의 실체를 밝혀달라고 부탁하게 된다. 핼러윈 밤, 베니스 운하 위 위치한 고풍스러운 저택의 주인이자 1년 전 사랑하는 딸을 잃고 깊은 상실에 빠진 로웨나 드레이크의 초대로 교령회에 참석한 이들은 미스터리한 심령술사 조이스 레이놀즈가 죽은 영혼의 목소리를 전하는 광경을 보며 혼란에 빠지게 된다. 갑자기 발생한 끔찍한 살인 사건에 실체 없는 용의자를 쫓던 에르큘 포와로는 자신의 모든 믿음이 흔들리는 경험을 하며 충격에 빠지게 되는데....",
      popularity: 133.884,
      poster_path: "/dUQdookYulZV9sTIEvAuAu1Ptxv.jpg",
      release_date: "2023-09-13",
      title: "베니스 유령 살인사건",
      video: false,
      vote_average: 6.8,
      vote_count: 601,
    },
    {
      adult: false,
      backdrop_path: "/urDWNffjwmNi5IQaezw9GwqkUXa.jpg",
      genre_ids: [12, 14],
      id: 767,
      original_language: "en",
      original_title: "Harry Potter and the Half-Blood Prince",
      overview:
        "어둠의 세력이 더욱 강력해져 머글 세계와 호그와트까지 위협해온다. 위험한 기운을 감지한 덤블도어 교수는 다가올 전투에 대비하기 위해 해리 포터와 함께 대장정의 길을 나선다. 볼드모트를 물리칠 수 있는 유일한 단서이자 그의 영혼을 나누어 놓은 7개의 호크룩스를 파괴하는 미션을 수행해야만 하는 것! 또한 덤블도어 교수는 호크룩스를 찾는 기억여행에 결정적 도움을 줄 슬러그혼 교수를 호그와트로 초청한다. 한편 학교에서는 계속된 수업과 함께 로맨스의 기운도 무르익는다. 해리는 자신도 모르게 지니에게 점점 끌리게 되고, 새로운 여자 친구가 생긴 론에게 헤르미온느는 묘한 질투심을 느끼는데...",
      popularity: 113.362,
      poster_path: "/yrGlb3HLtjGp39mv4MJ5UuIHcj4.jpg",
      release_date: "2023-09-06",
      title: "해리 포터와 혼혈왕자",
      video: false,
      vote_average: 7.7,
      vote_count: 18174,
    },
    {
      adult: false,
      backdrop_path: "/eiIvFiqOClwNX3nUmRlEmNarFCk.jpg",
      genre_ids: [10749, 35],
      id: 1001811,
      original_language: "en",
      original_title: "My Big Fat Greek Wedding 3",
      overview:
        "툴라와 이안 부부는 자신의 고향에서 뿌리를 찾아 달라는 아버지의 유언을 들어 드리기 위해 난생 처음 가족들과 함께 고향인 그리스의 작은 마을로 여행을 떠난다. 무언가를 숨기는 듯한 딸 패리스부터 그녀의 전 썸남 아리스토텔레스, 그리스 미신쟁이에 잔소리 대장인 불라와 프리다 이모, 세상 천진난만한 동생 닉까지 뭉칠수록 더 별난 이들은 도착한 그리스 마을에서 예상치 못한 비밀과 사건을 마주하며 우여곡절을 겪기 시작하는데…",
      popularity: 102.691,
      poster_path: "/8p7y5v92YYCeemkRbdF07rL1Oq2.jpg",
      release_date: "2023-09-20",
      title: "나의 그리스식 웨딩 3",
      video: false,
      vote_average: 6.7,
      vote_count: 46,
    },
    {
      adult: false,
      backdrop_path: "/5Jfk2p3iGrChUKkl0cBD5krr2u8.jpg",
      genre_ids: [16, 10749],
      id: 998731,
      original_language: "ja",
      original_title: "映画 佐々木と宮野ー卒業編ー",
      overview:
        "여성스러운 얼굴이 콤플렉스인 고등학교 2학년 ‘미야노’와 불량해 보이는 3학년 선배 ‘사사키’. BL 만화를 빌려 주면서 시작된 두 사람은 마침내 사랑에 빠진다. 어느덧 계절은 겨울로 바뀌고 ‘사사키’의 졸업이 코 앞으로 다가온다 두 사람은 함께하는 고교 생활을 소중하게 보내지만, 졸업이 다가올수록 애틋한 마음은 커져만 가는데… 고민도 불안도 날려 버리고, 언제나 아껴 주고 싶은 마음을 전하고 싶어!",
      popularity: 78.075,
      poster_path: "/4XeVvKoPKl5Mbiu6ZN3esMt51e7.jpg",
      release_date: "2023-09-06",
      title: "극장판 사사키와 미야노 - 졸업편",
      video: false,
      vote_average: 6.1,
      vote_count: 21,
    },
    {
      adult: false,
      backdrop_path: "/lZiaFbbLfqhO2PyyuiJrMQ576Ym.jpg",
      genre_ids: [27, 53, 10752],
      id: 1032666,
      original_language: "en",
      original_title: "Bunker",
      overview:
        "1차 세계대전 중 땅속에 갱도를 파듯 만들어진 의문스런 벙커에 갇힌 한 무리의 미국과 영국 군인들. 서서히 서로를 믿지 못하고 경계하게 만드는 불순한 존재에 직면한다. 그들 사이에 편집증과 두려움이 커지고 결국 죽고 죽이는 갈등이 폭발한다, 그리고 군인들은 벙커에 숨어서 도사리며 먹이를 노리고 있는 진정한 악마와 직면한다.",
      popularity: 86.273,
      poster_path: "/wkzQmebaktKnlqy6zakoDS0yxdR.jpg",
      release_date: "2023-09-14",
      title: "지옥갱",
      video: false,
      vote_average: 7.6,
      vote_count: 12,
    },
    {
      adult: false,
      backdrop_path: "/nV4nOG6ZCK8orRL7T5wXXgMdM0N.jpg",
      genre_ids: [10402, 35, 18],
      id: 1059811,
      original_language: "en",
      original_title: "Flora and Son",
      overview:
        "젊은 싱글맘 플로라(이브 휴슨)는 우연히 발견한 낡은 어쿠스틱 기타를 아들 맥스(오렌 킨런)에게 선물하지만 반항심 가득한 아들은 이를 거절한다. 직접 기타를 연주해 보기로 마음먹은 플로라, LA의 뮤지션 제프(조셉 고든 레빗)와 가까워지며 본격적인 기타 레슨이 시작된다. 한편, 음악을 알아갈수록 매일매일 새로운 감정도 함께 깨달아 가는 플로라. 어느 날 우연히 맥스가 남몰래 음악을 만들어 왔다는 사실을 알게 되고, 언제나 불협화음이던 아들과의 관계 역시 음악과 함께 점차 변화하기 시작하는데…",
      popularity: 65.176,
      poster_path: "/6Lb7OZWCfh9J2Yu9pbq9vkU29hm.jpg",
      release_date: "2023-09-22",
      title: "플로라 앤 썬",
      video: false,
      vote_average: 7,
      vote_count: 57,
    },
    {
      adult: false,
      backdrop_path: "/qAvou7F5P4VcIR72JzzrnKEQSN3.jpg",
      genre_ids: [12, 14, 10751],
      id: 630,
      original_language: "en",
      original_title: "The Wizard of Oz",
      overview:
        "회오리 바람에 휩쓸려 오즈의 나라로 내던져진 도로시는 집으로 되돌아갈 수 있는 유일한 길이 위대한 오즈의 마법사를 만나는 것임을 알고 그를 찾아 긴 여정이 시작된다. 도로시는 애견 토토와 함께 노란 길을 따라 오즈의 마법사가 사는 에메랄드 시티로 향한다. 도중에 만난 세 명의 친구들, 지능을 얻고자 하는 허수아비와 심장을 원하는 양철 나뭇꾼, 용기를 가지고 싶어하는 겁장이 사자와 함께 오즈의 마법사에게 자신의 소원이 이루어지도록 부탁하기 위해 도로시와 함께 경쾌한 발걸음을 옮긴다. 그러나 도로시 일행을 방해하기 위해 뒤쫓아오는 서쪽 나라 마녀의 검은 그림자.",
      popularity: 51.393,
      poster_path: "/9FzHxca1OybjwOdTmWLfhdD4u0g.jpg",
      release_date: "2012-05-03",
      title: "오즈의 마법사",
      video: false,
      vote_average: 7.6,
      vote_count: 5125,
    },
    {
      adult: false,
      backdrop_path: "/wNYUv8u5Z0AI4dkyxGyet7eLEWm.jpg",
      genre_ids: [18],
      id: 945675,
      original_language: "zh",
      original_title: "一周的朋友",
      overview:
        "일주일마다 친구에 대한 기억을 잃는 전학생 ‘린샹즈’ 병 때문에 자발적 아싸가 돼버린 그녀에게 성화 재수학원 최고 인싸 3인방 ‘쉬유수’, ‘송샤오난’, ‘장우'가 다가온다.  “일주일만 기억해도 상관없어. 일주일간 친구 하면 되잖아!” 머리가 좋아지는 호박죽, 기억력 증진 댄스, 깜찍한 유수표 엄지 인형까지! 세 사람은 샹즈의 단 하나뿐인 ‘일주일간 친구’가 되기 위해 고군분투하고, 샹즈는 그들과의 추억을 일기장에 채워 나가기 시작한다.",
      popularity: 49.746,
      poster_path: "/bCp45FrpSWD0mEx2EGHkvxOs2OK.jpg",
      release_date: "2023-09-06",
      title: "일주일간 친구",
      video: false,
      vote_average: 5.7,
      vote_count: 110,
    },
    {
      adult: false,
      backdrop_path: "/6fYTLy4QE55BgMiHF3Co7bErjry.jpg",
      genre_ids: [10752, 53, 28, 12, 9648, 878, 18],
      id: 1018494,
      original_language: "en",
      original_title: "Operation Seawolf",
      overview:
        "2차 세계대전 마지막 날 독일은 남은 무기로 미국과 미군을 무찔러 최후의 승리 쟁취를 갈망한다. 독일 해군과 마지막으로 남은 U보트 함대는 남은 병력을 총동원해 미국의 뉴욕을 공격할 작전을 펼치는데.... 1, 2차 세계대전을 겪은 독일의 한스 케슬러(돌프 룬드그렌) 함장은 전세를 뒤집는 데 협력하기 위해 소집되고 ‘씨울프’로 알려진 작전을 시작한다.",
      popularity: 48.248,
      poster_path: "/9C0zI8g8KDOEhJq1jc64l0SnlQe.jpg",
      release_date: "2023-09-21",
      title: "작전명 씨울프",
      video: false,
      vote_average: 5.9,
      vote_count: 86,
    },
    {
      adult: false,
      backdrop_path: "/5qsyqA7FeYRymBmNbPBqBgqWPO4.jpg",
      genre_ids: [12, 35, 10751],
      id: 9340,
      original_language: "en",
      original_title: "The Goonies",
      overview:
        "은행에 잡힌 저당으로 인해 곧 철거될 한 변두리 동네에서 아이들이 보물지도 한 장을 찾아낸다. 이 지도가 17세기 중엽 영국 해군과 싸우다 패하여 해저동굴에 숨어들어갔다는 '애꾸눈 윌리'가 보물을 숨겨둔 장소를 나타낸 것임을 알고 아이들은 모험을 시작한다. 해저 동굴의 입구인 등대 식당에서 위조지폐를 만드는 악당들에게 심한 곤욕을 치른 후 탈출한 아이들은 식당 지하실부터 해저 동굴로 들어가 한없는 통로를 헤쳐 나간다. 마침내 지도가 표시한 지점에 당도하여 보물을 손에 넣게 되지만 아이들은 악당들에게 잡혀 손에 들었던 금은 보화는 내동뎅이친 채 탈출한다. 그러나 우연히 들고나온 한 자루의 보물이 철거될 동네를 구하게 되어 아이들의 모험은 보석처럼 빛을 발한다.",
      popularity: 33.499,
      poster_path: "/w4AKh5YDOwUKqrnuyDZkY83Urjn.jpg",
      release_date: "1986-07-19",
      title: "구니스",
      video: false,
      vote_average: 7.5,
      vote_count: 5273,
    },
    {
      adult: false,
      backdrop_path: "/cOF7XiobQU4TC2tKDPXJ8d2nULP.jpg",
      genre_ids: [28, 53],
      id: 1024127,
      original_language: "en",
      original_title: "King of Killers",
      overview:
        "세계 최고의 킬러들 앞으로 초대장이 도착한다 한 곳에 모인 킬러들은 킬러들의 왕을 암살하고 최고의 킬러를 가리는 시합에 초청된 것 생존 게임이 시작되면, 단 한 놈만 살아남는다! 역대급 킬러 서바이벌을 만난다! 최후의 승자를 확인하라!",
      popularity: 46.778,
      poster_path: "/5afJkpvjo8vE85SFb3HWAHrfhcf.jpg",
      release_date: "2023-10-05",
      title: "킹 오브 킬러스",
      video: false,
      vote_average: 7,
      vote_count: 64,
    },
    {
      adult: false,
      backdrop_path: "/734OpJqPOVfI35yMGvPcieBI03g.jpg",
      genre_ids: [53, 27],
      id: 1014840,
      original_language: "tl",
      original_title: "Bula",
      overview:
        "세탁소에서 일하는 ‘멜디’는 남몰래 고객들의 옷을 이용해 그녀만의 은밀한 판타지를 즐긴다. 그러다 매력적인 경찰관 ‘팔마’를 만나고 그 남자를 손에 넣기로 결심하는데…",
      popularity: 31.741,
      poster_path: "/Q71kmkvWYF6Zclq1Ie5R7nm75m.jpg",
      release_date: "2023-09-26",
      title: "은밀한 판타지걸",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/2J6RdAjLzrq2e4f6ztw0dW5tZfR.jpg",
      genre_ids: [18, 10749, 14],
      id: 1037348,
      original_language: "ja",
      original_title: "わたしの幸せな結婚",
      overview:
        "사이모리 가문의 이능을 이어받지 못해 집안의 미움을 받던 ‘미요’는 쿠도 가문의 당주이자 냉정한 이능력자 ‘키요카’와 갑작스러운 정략결혼을 하게 된다. 원하지 않은 정략결혼으로 ‘미요’를 냉대하던 ‘키요카’는 이전의 약혼자들과는 다른 그녀의 모습에 점차 빠져들게 되고, ‘미요’ 역시 무자비한 줄로만 알았던 ‘키요카’의 다정한 모습에 자꾸 설레기 시작한다. 그렇게 ‘키요카’와 ‘미요’가 서로의 마음을 알아가던 중 ‘미요’는 자신에게 숨겨진 능력이 있다는 것을 깨닫게 되고, 그녀의 이능은 두 사람의 행복한 결혼을 방해하게 되는데…",
      popularity: 23.773,
      poster_path: "/7NsnLIuztqLgjoKema2TwKhsBRh.jpg",
      release_date: "2023-10-11",
      title: "나의 행복한 결혼",
      video: false,
      vote_average: 6.6,
      vote_count: 8,
    },
    {
      adult: false,
      backdrop_path: "/hcWXnOL7ScXpFQVjJruYUODeQxX.jpg",
      genre_ids: [9648, 35, 53, 36],
      id: 1066298,
      original_language: "zh",
      original_title: "满江红",
      overview:
        "송나라 재상 진회의 주둔지에서 금나라의 사신이 살해 당한다.  범인은 황제에게 바칠 밀서를 훔쳐 사라진 상황. 진회는 범행을 부인하는 유력 용의자 장다에게 목숨을 미끼로 밀서의 행방을 찾으라 명한다. 각기 다른 목적으로 밀서를 찾아야만 하는 6인! 주어진 시간은 단 2시간 뿐! 반드시 밀서를 차지해야만 한다!",
      popularity: 26.852,
      poster_path: "/zNQbQhbzzp6bubs5lv3S4mfo1SM.jpg",
      release_date: "2023-10-11",
      title: "만강홍: 사라진 밀서",
      video: false,
      vote_average: 5.8,
      vote_count: 96,
    },
    {
      adult: false,
      backdrop_path: "/4hAhZ66n5iasGtSYHTFg6oGdJk0.jpg",
      genre_ids: [53, 27, 878],
      id: 660942,
      original_language: "no",
      original_title: "De uskyldige",
      overview:
        "이다와 안나는 새로운 아파트로 이사한 직후, 또래인 벤자민, 아이샤와 친구가 된다. 네 명의 아이들은 어른이 개입하지 않는 순간, 특별한 잠재력을 깨워나가기 시작하고 벤자민은 능력을 이용해 사람들을 조정할 수 있게 된다. 단순한 호기심과 장난으로 행해지던 어떤 일들이, 급기야 분노라는 감정과 이어지고 결국 친구들을 비롯해 주변에 위협을 가하기 시작하는 벤자민. 가장 순수하고, 본능적이었던, 그래서 더욱 파괴적이고 잔인할 수 있었던 잔혹한 동심의 세계가 펼쳐진다!",
      popularity: 18.667,
      poster_path: "/tNJ2oOuTPHny3x633DwwKDnc5mQ.jpg",
      release_date: "2023-09-06",
      title: "이노센트",
      video: false,
      vote_average: 6.9,
      vote_count: 454,
    },
    {
      adult: false,
      backdrop_path: "/gEt8nXeSIAZB0xzjeUO6aeH1YnP.jpg",
      genre_ids: [80, 18],
      id: 1028684,
      original_language: "ko",
      original_title: "화란",
      overview:
        "희망도 미래도 없는 동네. 이곳에서 태어나 다른 곳은 가본 적 없는 18살 소년 연규는 반복되는 새아버지의 폭력 속에서 돈을 모아 엄마와 같이 네덜란드로 떠나는 것이 유일한 희망이다. 이곳에서 나고 자라 지금은 조직의 중간 보스가 된 치건. 일찌감치 세상은 지옥이란 걸 깨닫고 자신만의 방식으로 살아간다. 어느 날 동생 하얀을 지키기 위해 싸움을 하게 된 연규. 합의금이 절실한 연규에게 치건이 도움을 주고 이를 계기로 연규는 치건의 조직에서 새로운 삶을 시작한다. 무섭고 서툴지만 친형 같은 치건을 따르며 조금씩 적응해 가는 연규. 치건의 신뢰를 받으며, 조직에서 살아남기 위해 점점 위험한 상황에 빠져들기 시작하는데…",
      popularity: 16.481,
      poster_path: "/1cCi5Y4mBkpvtbxhDJPIRccCQrP.jpg",
      release_date: "2023-10-11",
      title: "화란",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/3mvV2BXwZnQdUuvGECaHoUjxB3d.jpg",
      genre_ids: [53, 27],
      id: 730167,
      original_language: "en",
      original_title: "The Reef: Stalked",
      overview:
        "놈의 사냥터에 뛰어들었다! 거대 식인상어와 맞서 살아남아라!  태평양 먼 바다 한가운데, 굶주린 식인상어의 무차별 인간사냥이 시작됐다!  작은 카약 보트 위 오로지 낡은 패들 뿐!",
      popularity: 20.113,
      poster_path: "/qj6AUoqKmBUORB0nrf2CoG8Sme8.jpg",
      release_date: "2023-09-20",
      title: "더 리프: 언더 워터",
      video: false,
      vote_average: 6,
      vote_count: 177,
    },
    {
      adult: false,
      backdrop_path: "/9ija3FGgnpqNfIXlaeQ7Tp8gITY.jpg",
      genre_ids: [16, 18, 10749, 14],
      id: 916192,
      original_language: "ja",
      original_title: "夏へのトンネル、さよならの出口",
      overview:
        "소원을 이루어 주지만 안팎의 시간이 다르게 흐르는 '우라시마 터널'을 발견한 고등학생 '카오루'와 전학생 '안즈' 터널의 비밀을 알아내기 위해 뜨거웠던 여름을 함께 보낸 두 사람은 어느새 서로에게 가장 소중한 존재가 되는데...",
      popularity: 21.874,
      poster_path: "/gwith9cdwf5ejpeRp0hYCIPaQRe.jpg",
      release_date: "2023-09-14",
      title: "여름을 향한 터널, 이별의 출구",
      video: false,
      vote_average: 7.8,
      vote_count: 60,
    },
    {
      adult: false,
      backdrop_path: "/uljTV5en1IDNys7w7MLf5DAOTUD.jpg",
      genre_ids: [16, 35, 10402, 10751],
      id: 812204,
      original_language: "en",
      original_title: "Rock Dog 2: Rock Around the Park",
      overview:
        "드림쏭 이후 1년, ‘버디’와 그의 밴드 ‘트루 블루’는 팬들의 열렬한 사랑을 받으며 눈의 마을의 인기 스타가 된다. ‘트루 블루’의 음악과 화려한 퍼포먼스 실력을 본 엔터테인먼트계의 거물 ‘랭’은 월드 클래스 스타 ‘리틀 폭시’와의 세계 투어 콘서트를 제안하고, ‘트루 블루’는 꿈을 위해 세계 투어 버스에 오른다. 하지만 ‘랭’의 친절한 제안에는 ‘버디’의 음악 에너지를 훔쳐 세계를 장악하려는 음흉한 계획이 숨겨져 있었는데.. 과연 ‘버디’는 ‘랭’으로부터 음악 에너지를 되찾고, 진정한 뮤직 쏘울로 세계를 지켜낼 수 있을까? 10월, 다시 함께 노래해!",
      popularity: 18.488,
      poster_path: "/v58tZuxYwuPc19AgtQ78cYKLRSj.jpg",
      release_date: "2023-10-03",
      title: "드림쏭2",
      video: false,
      vote_average: 6.5,
      vote_count: 103,
    },
    {
      adult: false,
      backdrop_path: "/bBXxN4QMa1FQ6UbCDJmXoZuhgeW.jpg",
      genre_ids: [28, 53, 9648],
      id: 950253,
      original_language: "ko",
      original_title: "천박사 퇴마 연구소: 설경의 비밀",
      overview:
        "대대로 마을을 지켜 온 당주집 장손이지만  정작 귀신은 믿지 않는 가짜 퇴마사 천박사. 사람의 마음을 꿰뚫는 통찰력으로 온갖 사건을 해결해온 그에게 귀신을 보는 의뢰인 유경이 찾아와 1억원이라는 수임료로 거절하기 힘든 제안을 한다. 천박사는 파트너 인배와 함께 유경의 집으로 향하고 그곳에서 벌어지는 사건을 쫓으며 자신과 얽혀 있는 부적인 설경의 비밀을 알게 되는데…",
      popularity: 18.064,
      poster_path: "/2tkotVho0wS2uszaxEt5yB2zAv9.jpg",
      release_date: "2023-09-27",
      title: "천박사 퇴마 연구소: 설경의 비밀",
      video: false,
      vote_average: 10,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/ubty43lOcYeeWMnWxszdNsrzf1z.jpg",
      genre_ids: [16, 12, 35],
      id: 809717,
      original_language: "de",
      original_title: "Peterchens Mondfahrt",
      overview:
        "사라진 아내와 자신의 한 쪽 팔을 찾기 위해 용감하고 동물을 사랑하는 인간을 찾는 딱정벌레. 그리고 그의 소원을 들어주기 위해 달나라 여행을 떠나는 ‘피터’와 ‘앤’. 하지만 달나라엔 우주 정복을 꿈꾸는 ‘문맨’이 있었고 결국 동생 ‘앤’이 납치를 당하게 되는데… 납치된 동생을 되찾기 위한 피터의 마법 같은 달나라 여행이 시작된다!",
      popularity: 15.848,
      poster_path: "/efZmHuIyafAB1YSIQhh8f10AxNE.jpg",
      release_date: "2023-09-28",
      title: "문바운드",
      video: false,
      vote_average: 6.4,
      vote_count: 83,
    },
    {
      adult: false,
      backdrop_path: "/hz4eqbxTQAQ3ZSFQAVP5GTfOh1N.jpg",
      genre_ids: [18],
      id: 785398,
      original_language: "pl",
      original_title: "IO",
      overview:
        "가련한 눈망울의 회색 당나귀 EO는 세상의 전부였던 서커스단으로부터 구조된 뒤, 폴란드와 이탈리아를 가로지르는 긴 여정에 오른다. 평화로운 농장, 훌리건으로 가득한 축구장, 공포의 소시지 공장, 쇠락 직전의 저택... 다양한 공간을 오가며 겪은 인간 세계는 다정하면서도 잔혹하다.",
      popularity: 19.615,
      poster_path: "/c5h01Rp1L8pBTRJdBMGCZEEGvQj.jpg",
      release_date: "2023-10-03",
      title: "당나귀 EO",
      video: false,
      vote_average: 6.6,
      vote_count: 245,
    },
    {
      adult: false,
      backdrop_path: "/ss7yKhQDAXohbiLyF8H4ngpBTwD.jpg",
      genre_ids: [53, 80],
      id: 9558,
      original_language: "en",
      original_title: "King of New York",
      overview:
        "한때 마약 왕이었던 프랭크 화이트는 오랜 징역형을 마친 후, 뉴욕으로 돌아와 자신의 사업에 방해되는 인물들을 제거해 나간다. 그 과정에서 총격 살인 사건을 벌인 부하들이 경찰에 체포되자 유능한 변호사를 통해 막대한 보석금을 내고 그들을 석방시킨다. 그리고 자신이 예전에 살던 동네의 병원을 현대화하기 위해 마약 사업으로 번 돈을 기부 하며 정치계와 손을 잡는 등 점점 거물이 되어 간다. 한편 이러한 과정을 알고 있는 경찰 몇 명이 상부의 허락도 없이 프랭크 일당을 습격을 하는데…",
      popularity: 12.39,
      poster_path: "/pmYueE8Lk4CDU0UcbBAbXpUmZfh.jpg",
      release_date: "1991-11-30",
      title: "킹 오브 뉴욕",
      video: false,
      vote_average: 6.7,
      vote_count: 564,
    },
    {
      adult: false,
      backdrop_path: "/eXDkeWY3EGBhAPL5y8Jk7aonwu4.jpg",
      genre_ids: [878, 35, 18],
      id: 889675,
      original_language: "en",
      original_title: "The Pod Generation",
      overview:
        "그리 머지않은 미래의 뉴욕, 레이첼과 앨비 커플은 기술의 발달에 따라 더욱더 편리한 삶을 살고 있다. 떠오르는 기술 회사의 중역인 레이첼은 자궁 센터의 탐나는 자리를 차지한다. 이곳은 분리 가능한 인공 자궁, 팟을 통해 커플들에게 편리하게(또한 부담을 나누며) 아이를 가질 기회를 제공한다. 그런데 자연에 깊은 애정을 지닌 식물학자인 앨비는 자연 임신을 원한다. 하지만 왜 그게 ‘자연스러운’ 것인가? 레이첼의 AI 테라피스트도 말한다. 이렇게 해서 부모가 되는 목표를 향한 기술로 포장된 길이 시작된다.",
      popularity: 14.394,
      poster_path: "/5li7nsDtJlX2pBpVUn3lS0onQ6N.jpg",
      release_date: "2023-10-03",
      title: "팟 제너레이션",
      video: false,
      vote_average: 5.8,
      vote_count: 16,
    },
    {
      adult: false,
      backdrop_path: "/hag9edxgL2RgG9FMfqAV0KgjPK0.jpg",
      genre_ids: [18],
      id: 803700,
      original_language: "it",
      original_title: "Le otto montagne",
      overview:
        "도시에 사는 피에트로와 산에 남은 유일한 아이 브루노. 알프스에서 만나 친구가 된 두 소년은 자연을 누비며 우정을 나눈다. 그 후 성인이 된 피에트로는 아버지 조반니가 세상을 떠난 뒤 산으로 돌아오고 브루노와 재회한다. 여덟 개의 산과 바다를 여행하는 자와, 태산의 정상에 오른 자 중에 누가 더 큰 깨달음을 얻었을까? 멀리 네팔을 떠도는 피에트로는, 후자의 삶을 갈망했던 아버지와 산의 무게를 껴안은 친구 브루노의 삶을 생각한다.",
      popularity: 18.992,
      poster_path: "/73bI5aLx2tFBDow3H09htyYn1UV.jpg",
      release_date: "2023-09-20",
      title: "여덟 개의 산",
      video: false,
      vote_average: 7.7,
      vote_count: 515,
    },
    {
      adult: false,
      backdrop_path: "/tMT3tsh7lXJTkHq4Gjq1XkNkgOr.jpg",
      genre_ids: [18, 35],
      id: 941045,
      original_language: "ko",
      original_title: "화사한 그녀",
      overview:
        "인생 역전 한방을 꿈꾸는 화사한 작전꾼 지혜. 매번 허당한 실력으로 허탕만 치던 그녀에게 600억이라는 일생일대의 기회가 찾아왔다. 실패는 사치다!라는 모토 아래 영혼까지 끌어 모은 마지막 작전을 시작하는데…",
      popularity: 11.279,
      poster_path: "/ed11pkcHGkfXlWG0chGadAfuWEW.jpg",
      release_date: "2023-10-11",
      title: "화사한 그녀",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/8RafTGqYqAN9FJzvC75USKmJCso.jpg",
      genre_ids: [10402, 99],
      id: 84334,
      original_language: "en",
      original_title: "Searching for Sugar Man",
      overview:
        "미국에선 ZERO, 남아공에선 HERO?!  팝 역사상 가장 신비로운 가수, ‘슈가맨’의 놀라운 이야기!  ● 본고장 미국: 음반 판매 6장, 아무도 알아주지 않는 비운의 가수!  ● 반대편 남아공: 밀리언셀러 히트가수, ‘엘비스’보다 유명한 슈퍼스타!  70년대 초, 우연히 남아공으로 흘러 들어온 ‘슈가맨’의 앨범은 수십 년간 가장 큰 사랑을 받으며 최고의 히트를 기록한다.  하지만 ‘슈가맨’은 단 두 장의 앨범만 남기고 사라져버린 신비의 가수!  전설의 ‘슈가맨’을 둘러싸고 갖가지 소문만 무성한 가운데,  두 명의 열성 팬이 진실을 밝히고자 그의 흔적을 찾기 시작한다.  그러나 단서라고는 오직 그의 노래 가사뿐!  기발한 추적 끝에 ‘슈가맨’에 대한 수수께끼를 풀었다고 생각한 순간,  그들은 상상하지도 못했던 놀라운 사실과 마주하게 되는데...!  지금부터 ‘슈가맨’의 리얼 기적이 시작됩니다!",
      popularity: 10.508,
      poster_path: "/2UlEwjiNud7V2aB2ghbkRbBjaPA.jpg",
      release_date: "2012-10-11",
      title: "서칭 포 슈가맨",
      video: false,
      vote_average: 7.9,
      vote_count: 837,
    },
    {
      adult: false,
      backdrop_path: "/uId66x2NKI9gBbcpGDi1krtN3pz.jpg",
      genre_ids: [18, 35],
      id: 901121,
      original_language: "ko",
      original_title: "거미집",
      overview:
        "1970년대 꿈도 예술도 검열당하던 시대. 성공적이었던 데뷔작 이후, 악평과 조롱에 시달리던 김감독은 촬영이 끝난 영화 거미집의 새로운 결말에 대한 영감을 주는 꿈을 며칠째 꾸고 있다. 그대로만 찍으면 틀림없이 걸작이 된다는 예감, 그는 딱 이틀 간의 추가 촬영을 꿈꾼다. 그러나 대본은 심의에 걸리고, 제작자 백회장은 촬영을 반대한다. 제작사 후계자인 신미도를 설득한 김감독은 베테랑 배우 이민자, 톱스타 강호세, 떠오르는 스타 한유림까지 불러 모아 촬영을 강행하지만, 스케줄 꼬인 배우들은 불만투성이다. 설상가상 출장 갔던 제작자와 검열 담당자까지 들이닥치면서 현장은 아수라장이 되는데…",
      popularity: 14.216,
      poster_path: "/hJfSFk3InWOO85IyAJ9qd06RgjM.jpg",
      release_date: "2023-09-27",
      title: "거미집",
      video: false,
      vote_average: 7,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/33t9M524eT5q8rE4STJxhpKB9ly.jpg",
      genre_ids: [18, 10749],
      id: 747779,
      original_language: "fr",
      original_title: "Un beau matin",
      overview:
        "여덟 살 난 딸, 투병 중인 아버지와 파리의 매일을 살아가고 있는 산드라는 어느 날 오랜 친구 클레망을 만나 새로운 사랑을 시작한다. 일과 가족, 사랑 사이에서 삶은 계속되고 때로는 눈물이 왈칵 쏟아지려 하지만 아침은 여느 때와 같이 찬란하게 찾아온다.",
      popularity: 10.479,
      poster_path: "/nuMQHu8xWYOHrEvUa88yrDyVfFo.jpg",
      release_date: "2023-09-06",
      title: "어느 멋진 아침",
      video: false,
      vote_average: 6.7,
      vote_count: 84,
    },
    {
      adult: false,
      backdrop_path: "/pFq6tKCgi3LFjzeGC7rEJsL6gK2.jpg",
      genre_ids: [18],
      id: 34308,
      original_language: "en",
      original_title: "Modigliani",
      overview:
        "1919년 파리, 뜨겁고 파괴적이었던 세기의 예술가 ‘모딜리아니’는 술과 마약에 중독되어 방탕하고 동료 예술과들과 종잡을 수 없는 기행을 일삼는다. “당신을 영혼까지 알게 되면, 그때 눈동자를 그릴게요” 어느 날, ‘모딜리아니’는 아름다운 ‘잔’에게 매료되어 운명적인 사랑에 빠진다. ‘잔’은 ‘모딜리아니’에게 영감을 주는 뮤즈로 그는 더욱 작품 활동에 몰두하게 된다. 하지만 아이를 낳은 ‘잔’은 이어지는 궁핍한 생활에 지쳐가고, ‘피카소’를 찾아가 전시회에 ‘모딜리아니’의 그림을 걸어달라고 부탁하면서 사이가 좋지 않았던 그들의 갈등은 더욱 심해진다. ‘모딜리아니’는 약물과 알코올 중독 증세로 건강마저 악화되면서 점점 엉망진창이 된다. 그는 파리에서 매년 개최되는 상금이 걸린 미술 경연대회에 작품을 내기로 결심하고, 애증의 라이벌 ‘피카소’까지 참가한다는 소식에 파리가 들썩이기 시작하는데…",
      popularity: 9.06,
      poster_path: "/gWQLJFK4Z0KRBZqgiVLT5nU3TIk.jpg",
      release_date: "2023-10-19",
      title: "모딜리아니",
      video: false,
      vote_average: 7,
      vote_count: 179,
    },
    {
      adult: false,
      backdrop_path: "/7W2z7wASYrXVX0EKt3hXwBmNzCL.jpg",
      genre_ids: [28, 53],
      id: 1035803,
      original_language: "en",
      original_title: "Detective Knight: Redemption",
      overview:
        "산타 복장을 한 폭파범이 뉴욕을 잔인하게 테러하는 가운데 감옥에서 구류 중이던 ‘나이트’는 테러리스트를 검거하는 대가로 배지를 돌려받기로 약속한다. 강철 같은 눈으로 정의로운 자에게는 자비를 베풀고 그렇지 못한 자에게는 무자비한 정의의 잣대를 들이미는 ‘나이트’. 과연 정의를 되찾고 모든 것을 되돌릴 수 있을까…",
      popularity: 12.045,
      poster_path: "/f3dYBqmbi1umZwdPGZ99q9iE02s.jpg",
      release_date: "2023-09-13",
      title: "리벤지 나이트",
      video: false,
      vote_average: 5.8,
      vote_count: 40,
    },
    {
      adult: false,
      backdrop_path: "/8ki3UBFOn0ghCa8oUDHaKhmAMO3.jpg",
      genre_ids: [16, 10751, 12, 28],
      id: 657561,
      original_language: "en",
      original_title: "The Wishmas Tree",
      overview:
        "일년 내내 따뜻하고 평화로운 생츄어리 마을에는 숲의 큰 자랑거리인 소원을 이뤄주는 마법의 소원 나무가 있다. 하지만 말썽쟁이 꼬마 주머니쥐, 케리는 마을에 야생의 겨울 왕국을 가져다 달라는 소원을 빌어 마을이 그만 꽁꽁 얼음 왕국으로 변해버린다. 죽어가는 소원 나무를 되살리고 마을을 구하기 위해 케리는 코딱지 진흙 늪과 안개 낀 수렁, 어둠의 협곡이 있는 야생의 정글 속으로 마법의 모험을 떠난다",
      popularity: 9.975,
      poster_path: "/quYc6vDzGWinjxzbsEnYeTho1kq.jpg",
      release_date: "2023-09-06",
      title: "생츄어리: 마법의 소원나무",
      video: false,
      vote_average: 6.5,
      vote_count: 70,
    },
    {
      adult: false,
      backdrop_path: "/tiKNQUipxfKQQXuUFnBprXtL7kM.jpg",
      genre_ids: [10749, 35],
      id: 1052433,
      original_language: "ko",
      original_title: "30일",
      overview:
        "지성과 외모 그리고 찌질함까지 타고난, 정열. 능력과 커리어 그리고 똘기까지 타고난, 나라. 영화처럼 만나 영화같은 사랑을 했지만 서로의 찌질함과 똘기를 견디다 못해 마침내 완벽한 남남이 되기로 한다. 그러나, 로맨스로 시작했지만 스릴러가 되어버린 결혼 생활의 끝을 딱 30일 앞두고 뜻밖의 사고로 기억을 잃어버리는데...",
      popularity: 9.949,
      poster_path: "/wq3PUoEQR8OImxuTV0THTFzYy7L.jpg",
      release_date: "2023-10-03",
      title: "30일",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/pRfBBi7q8cvM4NiKCh9cGmQdocV.jpg",
      genre_ids: [16, 18, 10402],
      id: 887870,
      original_language: "ja",
      original_title: "BLUE GIANT",
      overview:
        "세계 최고의 재즈 플레이어가 되겠다는 열정과 테너 색소폰만을 가슴에 품고 도쿄로 무작정 상경한 열여덟 소년 '다이'. 언제나 혼자서만 연습하던 그는 같은 꿈을 지닌 천재 피아니스트 '사와베'와 초보 드러머 '타마다'를 만나 밴드 'JASS'를 결성하고, 일본 최고의 재즈 클럽에서의 공연을 목표로 치열하고 격렬한 무대를 준비한다.",
      popularity: 8.704,
      poster_path: "/5ntHgYKnv70nHOPaqsW4ozKRKY8.jpg",
      release_date: "2023-10-18",
      title: "블루 자이언트",
      video: false,
      vote_average: 9.3,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: "/oLu4szayJyyWk9E1QkuiJrErbcu.jpg",
      genre_ids: [27],
      id: 1168166,
      original_language: "ko",
      original_title: "괴담만찬",
      overview:
        "욕망에 눈먼 이들이 겪는 죽음보다 더한 공포를 그린 <괴담만찬>은 댄스 챌린지, 입시, 모텔, 헬스장, 연구실, 먹방 등 1020 Zalpha 세대들에게 익숙한 소재에 얽힌 괴담들을 담은 영화",
      popularity: 10.646,
      poster_path: "/jkhDNfiVg9QPelVtZvyw4IphWQs.jpg",
      release_date: "2023-10-18",
      title: "괴담만찬",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/kzlOgKZcEQ5FWh1p9QZJd0v3lMQ.jpg",
      genre_ids: [99],
      id: 1022018,
      original_language: "ko",
      original_title: "페이오프",
      overview:
        "소설 「임꺽정」이 크게 성공하면서 출판사 관계자와 북에 있는 작가의 유족들이 저작권 문제를 해결하기 위해 만난다. 그 남·북 왕래는 걱정과 환대의 마음과 함께 정치, 경제, 문화, 각종 영역이 응축된 또 하나의 소설 같은 이야기가 된다.​",
      popularity: 6.34,
      poster_path: "/3p3mhrw8uTZZkdfhXZWHdqeqQ1c.jpg",
      release_date: "2023-10-11",
      title: "페이오프",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/dkRqcErje4ffPSso7wuoheycotC.jpg",
      genre_ids: [18, 36],
      id: 522925,
      original_language: "en",
      original_title: "Dalíland",
      overview:
        "달리의 예술 작품을 본능적으로 이해하며 제각기 다른 달리의 서명 수집, TV쇼 출연까지 챙겨보는 달리의 광팬이자 달리의 갤러리에서 일하는 제임스.  20년간 달리 부부가 겨울마다 묵는 뉴욕 세인트 레지스 호텔 1610호에 방문하며 우연한 기회로 달리의 조수를 제안받고 달리의 세계로 들어서게 된다. 매일 이어지는 화려한 파티와 그 속에서 만나는 각양각색의 인물들, 그리고 달리의 예술 활동의 근원이라 할 수 있는 그의 뮤즈 갈라를 통해 천재 예술가 달리의 진짜 얼굴을 보게 되는데! 길게 뻗은 콧수염, 녹아내리는 시계… 당신이 궁금했던 달리의 모든 것 ‘웰컴 투 달리랜드’!",
      popularity: 9.481,
      poster_path: "/vhIfmWeQErfTjX7csUaRM6F2G8i.jpg",
      release_date: "2023-10-18",
      title: "달리랜드",
      video: false,
      vote_average: 6.5,
      vote_count: 27,
    },
    {
      adult: false,
      backdrop_path: "/qcrActjV3aZl79xfbZ8Wxnqy9eC.jpg",
      genre_ids: [18],
      id: 581394,
      original_language: "ko",
      original_title: "1947 보스톤",
      overview:
        "1936년 베를린 올림픽, 세계 신기록을 세운 마라톤 금메달리스트 손기정. 기미가요가 울려 퍼지는 시상대에서 화분으로 가슴에 단 일장기를 가렸던 그는 하루아침에 민족의 영웅으로 떠올랐지만 일제의 탄압으로 더 이상 마라톤을 할 수 없게 된다. 광복 이후 1947년 서울, 제2의 손기정으로 촉망받는 서윤복에게 손기정이 나타나고 밑도 끝도 없이 보스톤 마라톤 대회에 나가자는 제안을 건넨다. 일본에 귀속된 베를린 올림픽의 영광을 되찾기 위해 처음으로 태극마크를 가슴에 새기고 달려 보자는 것! 운동화 한 켤레 살 돈도 없던 대한의 마라토너들은 미국 보스톤으로 잊을 수 없는 여정을 시작하는데…",
      popularity: 11.728,
      poster_path: "/n2O3hjrpS99wfy90dSh7oD6QYYV.jpg",
      release_date: "2023-09-27",
      title: "1947 보스톤",
      video: false,
      vote_average: 10,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/56Y2H9CcjFelVNtoltNUxx627bw.jpg",
      genre_ids: [10751, 35],
      id: 1148321,
      original_language: "ko",
      original_title: "가문의 영광: 리턴즈",
      overview:
        "돈과 권력을 쥐고 있는 전설의 장씨 가문. 가문의 수장 홍회장에게 골칫거리가 딱 하나 있는데, 비혼주의를 선언한 막내딸 진경이다. 어느 날 진경은 처음 본 남자 대서와 하룻밤을 보내게 되고 이 사실을 알게 된 장씨 가문은 일등 사윗감의 조건을 두루 갖춘 대서와 진경을 결혼시키기 위해 온갖 음모를 꾸미기 시작하는데… 장씨 가문에게 던져진 지상 최대의 과제! 세기의 결혼은 과연 성공할 수 있을까?",
      popularity: 7.174,
      poster_path: "/ozCUmnU6z7chpYXLcO3szIiNShr.jpg",
      release_date: "2023-09-21",
      title: "가문의 영광: 리턴즈",
      video: false,
      vote_average: 2.3,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: "/wbW4w4HvvzDavQCjUKtLMosyNn5.jpg",
      genre_ids: [18, 10749],
      id: 900379,
      original_language: "de",
      original_title: "Roter Himmel",
      overview:
        "뜨겁고 건조한 여름 발트해 해변. 네 명의 젊은 남녀가 숲속 별장에 모였다. 산불 소식이 들려오고 소방 헬기가 오가는 가운데 이들의 마음 속에도 욕망, 사랑, 질투, 분노의 걷잡을 수 없는 불길이 번지기 시작한다.",
      popularity: 7.906,
      poster_path: "/lgMLbDWoODpmxkso3Xc22woUyPW.jpg",
      release_date: "2023-09-13",
      title: "어파이어",
      video: false,
      vote_average: 7.3,
      vote_count: 35,
    },
    {
      adult: false,
      backdrop_path: "/ghSMYISXNxjduDuvzYoPYOI3yRk.jpg",
      genre_ids: [16, 10751],
      id: 753601,
      original_language: "fr",
      original_title: "Le Tour du monde en 80 jours",
      overview:
        "걱정 많은 엄마 때문에 세계여행이라는 꿈을 펼치지 못하던 왕소심 원숭이 ‘파스파르투’ 그리고 어느 날 ‘파스파르투’ 앞에 나타난 자칭(?) 모험 전문가 개구리 ‘필리어스’! 두 친구는 ‘파스파르투’를 무시하던 마을 주민들의 코를 납작하게 만들기 위해 80일간의 세계일주를 떠나게 되는데…",
      popularity: 10.018,
      poster_path: "/lDESZAiGCGB5bVevD2ZDOcReu5D.jpg",
      release_date: "2023-09-27",
      title: "80일간의 세계일주",
      video: false,
      vote_average: 5.6,
      vote_count: 49,
    },
    {
      adult: false,
      backdrop_path: "/t4QVBXlgE9zuRoanEFZvufDIgF5.jpg",
      genre_ids: [27],
      id: 987540,
      original_language: "ko",
      original_title: "치악산",
      overview:
        "산악바이크 동아리 산가자의 리더 민준과 팀원들은 라이딩 영상을 촬영하기 위해 치악산으로 향한다. 민준의 사촌 동생, 현지 아버지의 산장에 머물게 된 이들은 40년 전 현지 아버지가 치악산에서 실종되었다는 사실을 알게 되고 그날 밤부터 팀원 양배, 수아, 이삭을 비롯한 모두에게 정체를 알 수 없는 기이한 일들이 벌어지는데...",
      popularity: 9.664,
      poster_path: "/dsMmY1Le43aMdfRIuHSlikf4rXu.jpg",
      release_date: "2023-09-13",
      title: "치악산",
      video: false,
      vote_average: 5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/hkjOiIKeZ59XupKXVHGaLtHG1u.jpg",
      genre_ids: [35, 18],
      id: 935906,
      original_language: "en",
      original_title: "Scrapper",
      overview:
        "엄마가 세상을 떠나고 혼자 씩씩하게 살아가던 ‘조지’ 어느 날 초대한 적 없는 손님 ‘제이슨’이 제 집인 양 담벼락을 넘어온다. ‘제이슨’은 본인이 ‘조지’의 아빠라 주장하지만 머리부터 발끝까지 의심스러운 그의 말을 도무지 믿을 수 없다.",
      popularity: 7.077,
      poster_path: "/1wGmh1Rp7sowNc4wTALI7aupxwk.jpg",
      release_date: "2023-09-27",
      title: "스크래퍼",
      video: false,
      vote_average: 6.7,
      vote_count: 10,
    },
    {
      adult: false,
      backdrop_path: "/bBr0KBXmqKMvX1M62IU2efJz0L6.jpg",
      genre_ids: [99],
      id: 1032760,
      original_language: "es",
      original_title: "Memoria infinita",
      overview:
        "칠레의 저명한 저널리스트이자 피노체트 정권의 범죄를 기록한 작가 아우구스토와 배우이자 활동가이며 문화부 장관을 역임한 파울리나는 25년간 사랑을 이어온 백발의 연인이다. 8년 전 아우구스토가 알츠하이머 판정을 받은 이후, 악화되고 있는 병세 앞에 무기력함을 느낀다. 그러나 파울리나는 아우구스토가 끝까지 스스로를 잃어버리지 않도록, 타협하지 않는 헌신으로 함께 치열하게 싸우고자 한다. 서로의 얼굴을 어루만지는 손길을 따라 주름 하나하나에 애정과 슬픔의 기억들을 채우고, 인생이라는 극에서 천천히 퇴장하고 있는 그들의 깊고 진한 사랑은 절찬리 진행 중이다.",
      popularity: 10.532,
      poster_path: "/zTXgtFELvBdxznGCsnz47yJY4PL.jpg",
      release_date: "2023-09-20",
      title: "이터널 메모리",
      video: false,
      vote_average: 9.6,
      vote_count: 5,
    },
    {
      adult: false,
      backdrop_path: "/tKRQbdGp8jHaWicKr9Qq8TNJZdu.jpg",
      genre_ids: [18],
      id: 1086626,
      original_language: "ko",
      original_title: "믿을 수 있는 사람",
      overview:
        "한영은 중국에서 살았을 때 배운 중국어를 활용하여 중국어 관광통역안내사 자격증을 취득하고 가이드가 된다. 아직 익숙지 않은 환경에 적응해 가며 실적도 제법 쌓지만 함께 온 동생 인혁의 행방은 알 수가 없고 사드 배치로 중국인 관광객까지 줄어드는 등 한영의 삶은 시대의 흐름과 함께 계속적으로 변화를 맞이한다.",
      popularity: 8.64,
      poster_path: "/yhwzXIgApNTK2Y676oPkb79isBE.jpg",
      release_date: "2023-10-18",
      title: "믿을 수 있는 사람",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/8kgfR6KwCwc6WA2AY1wqBXkYpEy.jpg",
      genre_ids: [27, 9648],
      id: 964592,
      original_language: "ko",
      original_title: "잠",
      overview:
        "행복한 신혼부부 현수와 수진. 어느 날, 옆에 잠든 남편 현수가 이상한 말을 중얼거린다. 그날 이후, 잠들면 마치 다른 사람처럼 변하는 현수. 깨어나면 아무것도 기억하지 못하는 현수는 잠들면 가족들을 해칠까 두려움을 느끼고 수진은 매일 잠드는 순간 시작되는 끔찍한 공포 때문에 잠들지 못한다. 치료도 받아보지만 현수의 수면 중 이상 행동은 점점 더 위험해져가고 수진은 곧 태어날 아이까지 위험에 빠질지도 모른다는 생각에 갖은 노력을 다해보는데…",
      popularity: 5.524,
      poster_path: "/3kS3hle0qq9IijimAkQmvb4luXB.jpg",
      release_date: "2023-09-06",
      title: "잠",
      video: false,
      vote_average: 7.5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/gb04BegT1otvRcYkN5HMXUgXjQK.jpg",
      genre_ids: [28, 53],
      id: 1022921,
      original_language: "tl",
      original_title: "Pabuya",
      overview:
        "갱단 두목 페페는 라이벌 갱단 두목 조조와 세력 다툼을 벌이다 쫓기는 신세가 된다. 페페는 옛 연인 벨라에게 도움을 청하고 두사람은 잊고 살았던 애틋한 마음을 다시 확인한다. 하지만 페페에게 현상금을 걸리게 되고 벨라는 간직해 온 비밀이 밝혀지는데…",
      popularity: 8.368,
      poster_path: "/b8xqcxOgKtUSBDkuQGlPbtYHkie.jpg",
      release_date: "2023-09-21",
      title: "섹스 앤 머니",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/kQzTAzS72Itv2NkKsPwnjozrpw9.jpg",
      genre_ids: [18],
      id: 751519,
      original_language: "ja",
      original_title: "キネマの神様",
      overview:
        '도박을 좋아하여 아내(미야모토 노부코)와 가족에게 버림받은 남자 고우에게, "영화의 신"이 기적을 가져다주는 이야기. 과거 영화 촬영소에서 일하던 고우는 동료와 함께 꿈을 쫓고 있었지만, 두 사람이 식당의 아가씨(나가노 메이)에게 모두 연정을 품게 되어, 운명의 수레바퀴가 엇나가기 시작한다.',
      popularity: 3.217,
      poster_path: "/atH4d1p7vDgJafMuZougzMGE2aw.jpg",
      release_date: "2023-10-01",
      title: "키네마의 신",
      video: false,
      vote_average: 7,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: "/3m2KInF9d2rdV6vU7aN2y1GQDBG.jpg",
      genre_ids: [10749, 35],
      id: 1077310,
      original_language: "zh",
      original_title: "不能流泪的悲伤",
      overview:
        "어느 날, 집 앞에 도착한 카세트 테이프 한 장. 그 속엔 네가 보낸 우리의 이야기가 남겨져 있었다. 느닷없는 고백, 어쩌다 첫키스, 그렇게 시작된 우리의 평범한 연애. 고교시절, 나의 세상은 온통 너뿐이었지만 스무살, 우리는 또 다른 세상 밖으로 나가야만 했다. 어느날 내 앞에서 사라져 버린 너. 서로를 놓아버린 우리. 테이프 속에 담긴 추억은 잊으려 할수록 더욱 선명해지고 나는 무작정 너를 찾아나서기 시작한다.",
      popularity: 5.335,
      poster_path: "/suyMUwDd4xsAfaAsGJItoYfgK76.jpg",
      release_date: "2023-10-11",
      title: "기억해, 우리가 사랑한 시간",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/7B4isNNqqmjCaDtqljMvaDg2OU9.jpg",
      genre_ids: [99],
      id: 1058673,
      original_language: "en",
      original_title: "Kim's Video",
      overview:
        "\"마치 보물상자 같았어요. 킴스 비디오'에 들어가면 금광에 들어가는 이상한 기분이었어요\" 1980년 대 뉴욕 이스트빌리지에 자리잡은 영화광들의 성지, 미스터리한 한국인 '미스터 킴'의 비디오 대여점 '킴스 비디오'! 마틴 스콜세지, 쿠엔틴 타란티노, 코엔 형제, 로버트 드니로가 단골인 55,000 편의 컬렉션과 250,000명의 회원을 보유한 '킴스 비디오'가 사라졌다? '킴스 비디오'가 키운 미친 영화광들의 비디오 해방 프로젝트! 마피아보다 독하게 쫓는 무제한 렌탈 유니버스 지금, 플레이하시겠습니까?",
      popularity: 3.595,
      poster_path: "/9MhVt0RumvhinZHrLsVrHt3Vs5x.jpg",
      release_date: "2023-09-27",
      title: "킴스 비디오",
      video: false,
      vote_average: 8,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 1125324,
      original_language: "ko",
      original_title: "고인돌",
      overview:
        "영화 <고인돌>은 기원전 2333년 한반도 최초 부족국가 고조선 설립 직전의 이야기다. 고인돌 문화가 융성한 시대, 태양부족과 달 부족이 지석강을 경계로 적대관계에 놓여 있다. 태양부족장 딸 사스미와 달 부족장 아들 바우쩍은 사냥터에서 만나 운명적인 사랑에 빠진다. 그러나 그들의 사랑은 부족 간 전쟁으로 비화되고... 바우쩍은 사스미를 지키기 위해 달 부족장이 쏜 화살을 대신 맞고 죽는다. 아비가 아들을 죽인 상황이 된 것이다. 그리고 현재 고대인 바우쩍과 사스미는 성이 다른 남녀로 태어나 고고학 박사와 여고생의 신분으로 다시 만나는데...",
      popularity: 5.936,
      poster_path: "/xjoeTGzcz2kag1ebzHjHivG1HuV.jpg",
      release_date: "2023-10-19",
      title: "고인돌",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/f5FjEf3u4ybAKfqUainQwJhZPy2.jpg",
      genre_ids: [10402, 99],
      id: 1165656,
      original_language: "ko",
      original_title: "아이유 콘서트 : 더 골든 아워",
      overview:
        "아이유의 데뷔 15주년을 기념해 극장에서 개봉하는 첫 공연 실황 영화로, 눈과 귀를 황홀하게 만드는 아름다운 노래와 환상적인 무대연출로 올림픽주경기장을 가득 채웠던 우리들의 ‘골든 아워’를 스크린에 옮겼다.",
      popularity: 4.776,
      poster_path: "/z8AW2twgc2eg64GMPxSlwOOpTJV.jpg",
      release_date: "2023-09-13",
      title: "아이유 콘서트 : 더 골든 아워",
      video: false,
      vote_average: 10,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/e9BQ1uSCbGtffK3MeiYA5PRGLz6.jpg",
      genre_ids: [53, 18],
      id: 661931,
      original_language: "es",
      original_title: "La hija",
      overview:
        "소년원에 수감된 14살 소녀 ‘이리네’는 임신을 하게 되고 소년원 직원인 ‘하비에르’의 도움으로 소년원을 탈출한다. 아이를 가질 수 없었던 ‘하비에르’와 그의 아내 ‘아델라’는 외지고 험한 산속에 있는 자신들의 집으로 그녀를 데려가 보살핀다. 그녀가 편히 지낼 수 있도록 비밀스러운 거래를 제안하는 부부는 아이가 태어날 날을 손꼽아 기다리며 지극정성으로 보살핀다. 자신의 아이를 주는 대가로 탈출과 보살핌을 받아온 ‘이리네’는 출산이 다가오면서 아이에게 모성애를 느끼게 되고, 아이의 아빠인 ‘미구엘’과 뱃속의 아이까지 함께 할 날들을 기다리며 ‘하비에르’ 부부에게서 도망갈 계획을 세우는데..",
      popularity: 3.181,
      poster_path: "/jwS5YrMbslOpkIld7NUTq50h2Kz.jpg",
      release_date: "2023-10-19",
      title: "더 도터",
      video: false,
      vote_average: 6.2,
      vote_count: 25,
    },
    {
      adult: false,
      backdrop_path: "/cCBVpqqFHavVJofPCTHFfQWTuV2.jpg",
      genre_ids: [27, 9648],
      id: 1130899,
      original_language: "ja",
      original_title: "ミンナのウタ",
      overview:
        "방송국 창고에서 발견된 오래된 카세트테이프. 그 안에 담긴 정체불명의 허밍 소리를 들은 방송국 관계자들이 실종되기 시작하고, 인기 아이돌 ‘제너레이션즈’ 마저 테이프를 접한 후 저주 같은 공포에 시달린다. 급기야 콘서트를 앞두고 멤버가 실종되는 사태에 이르는데… 매니저는 상황을 해결하기 위해 급히 탐정을 고용하고 테이프에 얽힌 한 소녀의 미스터리한 사연을 마주한다. 모든 것은 카세트테이프에서 시작됐다! 재생하는 순간, 봉인된 ‘저주의 멜로디’가 깨어난다!",
      popularity: 2.497,
      poster_path: "/w20soUVMn9nYeNs9zfEuMfjhk25.jpg",
      release_date: "2023-10-04",
      title: "사나: 저주의 아이",
      video: false,
      vote_average: 8.5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/5tJKgghFE24RBpG20p7CLtWtKsQ.jpg",
      genre_ids: [18],
      id: 575768,
      original_language: "en",
      original_title: "Coming Home Again",
      overview:
        "위암 말기 선고를 받은 어머니를 위해 샌프란시스코 고향 집으로 돌아온 창래. 서로 떨어져 살게 되며 생긴 공백을 채우지 못한 두 사람은 점점 마음의 골이 깊어진다. 창래는 감정을 추스르지 못한 채, 어머니와의 추억이 가득 담긴 레시피로 가족을 위한 마지막 식사를 준비하기 시작하는데…",
      popularity: 2.984,
      poster_path: "/2MFaNvHrLaMowvJNjdOl1w1lU8W.jpg",
      release_date: "2023-09-23",
      title: "커밍 홈 어게인",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/ccNiNtIq2RQ8risEkUtSG5OXWkg.jpg",
      genre_ids: [18, 10752],
      id: 775271,
      original_language: "en",
      original_title: "Love in Country",
      overview:
        "베트남 전쟁에서 수세에 몰린 미군. 최정예 대원으로 베트콩의 총공격 정보를 가진 지도자를 탈출시키는 특수작전에 돌입한다. 험난한 전투 끝에 접선지에 도착하지만 예상치 못한 베트콩의 트랩과 내부 분열로 목숨을 건 이중 전투가 시작되는데…",
      popularity: 3.175,
      poster_path: "/v532Tw85JVV5sCCKECFyaVj4uTp.jpg",
      release_date: "2023-09-27",
      title: "피닉스 미션",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [10402],
      id: 1189526,
      original_language: "en",
      original_title: "The Fact Music Awards",
      overview: "",
      popularity: 4.712,
      poster_path: "/lbF23G8R3l2yHhzUzeGjeO8qe7b.jpg",
      release_date: "2023-10-10",
      title: "The Fact Music Awards",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/dAfvQUiq1BGpzZg9fdSvkOjPnQp.jpg",
      genre_ids: [27, 53],
      id: 1127546,
      original_language: "ko",
      original_title: "차박 - 살인과 낭만의 밤",
      overview:
        "모든 것이 완벽하게 행복한 부부 수원과 미유. 결혼 1주년을 맞아 떠난 둘만의 낭만적인 차박 여행은 낯선 누군가의 등장과 함께 순식간에 끔찍한 악몽으로 바뀐다.",
      popularity: 2.658,
      poster_path: "/rOGiPPqIiQKpfqOgLCWA1xUqTqi.jpg",
      release_date: "2023-09-13",
      title: "차박 - 살인과 낭만의 밤",
      video: false,
      vote_average: 4,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/njDzC6pFQKjqv60LpJq5LOiPHV7.jpg",
      genre_ids: [18],
      id: 1075840,
      original_language: "zh",
      original_title: "白塔之光",
      overview:
        "2년 전 이혼했고, 맛집 리뷰어인 왕년의 시인 구원통은 수십 년 만에 아버지의 존재를 확인하고 베이다이허로 그를 찾아간다. 원통의 협업 사진작가 원후이와 그와 동명인 원통의 누나는 둘 다 거침이 없어 보이지만 그들에게도 지우고 싶은 ‘그늘’은 있었다.",
      popularity: 1.922,
      poster_path: "/x9iM86JPxzvuTl9G9TVFfl6f0xO.jpg",
      release_date: "2023-10-08",
      title: "백탑지광",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/uj4ChlZG4014QhcfMwlExpI3Nz6.jpg",
      genre_ids: [18],
      id: 1114775,
      original_language: "ko",
      original_title: "우리의 하루",
      overview:
        "한때 배우로 일했던 상원(김민희)은 지금 선배 정수(송선미)의 거처에 머무르는 중이다. 어느 오후, 배우가 되고 싶다는 여자가 찾아와 상원의 이야기를 듣고자 한다. 시인 홍의주(기주봉)는 심장이 안 좋아져서 술 담배를 끊은 상태다. 젊은 감독이 시인에 대한 다큐멘터리를 찍기 위해 그의 집에 와 있다. 마침 시인을 동경해온 한 남자가 방문해 그에게 여러 질문을 던진다.",
      popularity: 1.768,
      poster_path: "/712BOyadfS8Dt56ymxEyahlqYOQ.jpg",
      release_date: "2023-10-19",
      title: "우리의 하루",
      video: false,
      vote_average: 7,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/m3CVpgdPospIf53mxaiOD5UIOBj.jpg",
      genre_ids: [10749],
      id: 846517,
      original_language: "zh",
      original_title: "再說一次我願意",
      overview:
        "너에게 첫눈에 반한 지 2225일째, 두근두근 설렘 가득 대망의 날이 밝았다!  프러포즈 D-DAY를 맞이한 ‘루크’는 ‘샤오차이’가 감동할 모습을 기대하며 분주한 하루를 보낸다. ☑ 마음을 전달할 반지 맞추기 ☑ 프러포즈를 도와줄 친구들과 사전 모임 ☑ 멋지게 꽃 단장하기 ☑ 여친 도착 전 리허설은 필수 마침내 오늘의 주인공 ‘샤오차이’가 도착하고 모든 게 완벽하다 생각한 순간, ‘루크’의 고백은 청천벽력 같은 거절과 함께 암전?! 그리고 다시, 프러포즈날의 아침이 밝았다?!",
      popularity: 2.265,
      poster_path: "/xbhoXMTzSsYIrHokOccsEaEFEkk.jpg",
      release_date: "2023-10-18",
      title: "세이 예스 어게인",
      video: false,
      vote_average: 5.5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/AeDEzkMrPSMOFpgxk2C2NR52Bvv.jpg",
      genre_ids: [99, 10402],
      id: 1189848,
      original_language: "ko",
      original_title: "바람 따라 만나리 : 김호중의 계절",
      overview:
        "3개월간 전국 6개 도시에서 10만 아리스와 함께했던 김호중의 첫 전국 투어 콘서트, 아리스트라! 제대 후 일년간 쉬지 않고 달려온 김호중이 지친 몸과 마음을 달래기 위해 떠난 여행. 대규모 오케스트라와 김호중의 천상의 목소리, 그리고 아리스의 환호가 공연장을 가득 채웠던 감동적인 콘서트 장면과 고군산도의 눈부신 풍경을 따라 여행하는 김호중의 행복한 순간이 스크린X 파노라마 뷰로 펼쳐진다.",
      popularity: 3.842,
      poster_path: "/tA6rPSrTCqE8urUDUOB1LTB31J3.jpg",
      release_date: "2023-10-17",
      title: "바람 따라 만나리 : 김호중의 계절",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/35O0yMGZDQOC0JBmONT6uL61fF2.jpg",
      genre_ids: [10749, 35, 14],
      id: 1079196,
      original_language: "ko",
      original_title: "봉태리",
      overview:
        "망해가는 제약회사의 사장은 나도 자연인이다 프로그램에 출연해 신약을 홍보한다는 기가 막힌 플랜을 만든다. 7년째 연애 중인 소영과의 결혼을 위해 내 집 마련이 인생 최대의 목표인 일우는 본인의 청약 대출을 위해 회사 존속이 중요하다. 게다가 연봉 200%까지 올려준다는 솔깃한 제안에 결국 그는 가짜 자연인이 되어 산골 봉태리로 들어가게 된다. 평생 경찰의 꿈만 쫓으며 위풍당당하게 캥거루족 삶을 살고 있는 봉숙은 세상 곳곳에 숨어있는 바퀴벌레같은 범죄자들을 다 잡아버리겠다는 의지가 무색하게 5년째 경찰공무원 시험에서 낙방을 하고 있다. 어느 날 봉숙의 부모는 모든 경제적 지원 중단을 선언하고, 봉숙은 가짜 청년농부가 되어 시험 자금을 벌어보겠다는 속셈으로 외할아버지가 살고 계신 산골 봉태리로 내려가게 된다. 그리고 봉태리에서 일어나는 의문의 신발도난사건. 봉숙은 신발도난사건의 유력한 용의자로 일우를 지목하고, 일우는 이런 봉숙이 가짜 자연인을 색출하러 온 진짜 경찰이라고 오해한다. 쫓고 쫓기는 가운데 봉숙은 범인 후보 일우에게 묘한 감정을 느끼게 되는데...",
      popularity: 3.842,
      poster_path: "/mJDvgZKboCjj8vUisZxoNNmZRts.jpg",
      release_date: "2023-10-11",
      title: "봉태리",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/3RBfNUG3j9HuxSgQUWDE1UhOtDt.jpg",
      genre_ids: [99],
      id: 493514,
      original_language: "zh",
      original_title: "青春",
      overview: "",
      popularity: 3.716,
      poster_path: "/7iVtOQm9A8dDGxeuSiYuWK2U7cK.jpg",
      release_date: "2023-10-05",
      title: "청춘(봄)",
      video: false,
      vote_average: 9,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/fVa6swVBCHlY9OE2HMcO5MapW1j.jpg",
      genre_ids: [80, 53],
      id: 956728,
      original_language: "ko",
      original_title: "폭로",
      overview:
        "신출내기 변호사 정민은 남편을 살해한 피고인 윤아의 국선 변호를 맡아 야비한 검사, 비밀스러운 판사, 의혹에 싸인 피고인 등에 둘러싸인 채 음모가 뒤얽힌 사건의 진실을 밝히고자 노력한다. 마지막 재판에서의 충격적인 폭로로 정민은 모든 것이 밝혀졌다고 생각하지만, 진실은 그가 모르는 곳에 숨겨져 있다.",
      popularity: 2.667,
      poster_path: "/pgzqE8rXv9zFsDB8y33S7JTl8Cn.jpg",
      release_date: "2023-09-30",
      title: "폭로",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/v6kyf3TeKlqckIIZ0j8VWoVXpN7.jpg",
      genre_ids: [18],
      id: 1182190,
      original_language: "ko",
      original_title: "4: 클린 아일랜드",
      overview: "",
      popularity: 1.693,
      poster_path: "/i1XGKZYlwGOgQxBbcJfvE4QgQGE.jpg",
      release_date: "2023-09-27",
      title: "4: 클린 아일랜드",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/hymzvvV5KlbBseLvXSDB2yfbeIS.jpg",
      genre_ids: [18],
      id: 877411,
      original_language: "ko",
      original_title: "절해고도",
      overview:
        "윤철은 조각가이지만 주로 인테리어 일을 하면서 생활을 유지한다. 그는 이혼한 아빠인데, 딸 지나는 아빠를 닮아 미술에 소질이 있지만 고등학교 생활에 적응하지 못하며 문제아로 낙인찍힌다. 한 편 윤철은 영지라는 매력적인 여인을 만나 늦은 나이에 사랑에 빠지게 된다.",
      popularity: 2.688,
      poster_path: "/t9l5QBrZxPP2yaaCSfXXjKa05pr.jpg",
      release_date: "2023-09-27",
      title: "절해고도",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 12, 16],
      id: 1172928,
      original_language: "ko",
      original_title: "번개맨: 더 비기닝",
      overview:
        "재미 있는 것도, 관심 있는 것도 없는 고등학생 지오. 하나뿐인 가족, 형 윤오와 함께 살며 블랙코퍼레이션사 폐기처리부에서 아르바이트를 하던 어느 날, 지오는 난데없이 번개에 맞아 번개 파워를 얻게 된다. 형 윤오가 교통사고로 갑작스럽게 사망하고, 형의 죽음 뒤에 블랙코퍼레이션의 음모가 있었음을 알게 된 지오는 형의 복수와 도시를 지키기 위해 번개맨이 되어 악당들과 맞서 싸워 나간다.",
      popularity: 1.621,
      poster_path: "/wqk3Vy2sSrSBRUUKkMsIhofJzeD.jpg",
      release_date: "2023-09-20",
      title: "번개맨: 더 비기닝",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/xWQlaHuPcllRp9wqPsJqPjCTQcX.jpg",
      genre_ids: [28, 18, 36],
      id: 1161406,
      original_language: "pa",
      original_title: "ਮਸਤਾਨੇ",
      overview: "",
      popularity: 2.991,
      poster_path: "/8vrlTSiMcNlnCQn6oNcgbbKbSn3.jpg",
      release_date: "2023-09-10",
      title: "ਮਸਤਾਨੇ",
      video: false,
      vote_average: 10,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 1190215,
      original_language: "ko",
      original_title: "Balgeunsori A",
      overview: "",
      popularity: 2.744,
      poster_path: "/oAwZkWvDbTIYKOavjxR6VNx94z9.jpg",
      release_date: "2023-10-11",
      title: "Balgeunsori A",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35],
      id: 1016604,
      original_language: "ko",
      original_title: "한탕",
      overview:
        "“에로영화도 예술이다.” 최고의 에로 영화를 찍기 위해 촬영장소로 점 찍어 놓은 으리으리한 별장을 섭외하기 위해 제작진들이 총 출동한다. 액션 영화라는 말에 별장 주인은 제작진과 모정의 딜을 하며, 순순히 촬영 장소로 제공을 해주고, 그들의 예술 작품은 순조롭게 진행되어만 가는 것 같은데... 출연하기로 한 배우가 촬영 당일 잠수를 타버리고, 급하게 배우를 섭외해야 하는 그때! 그들 앞에 나타난 구세주. 구세주의 등장으로 촬영은 다시 시작되지만 더 큰 사건에 휘말리게 되는데...",
      popularity: 1.58,
      poster_path: "/jNy3FLaDDnY76X6dd5gqQWQgLrA.jpg",
      release_date: "2023-09-07",
      title: "한탕",
      video: false,
      vote_average: 5,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/nvOrS60C5x3pL4aAY5hlT7S6jY7.jpg",
      genre_ids: [18, 10751],
      id: 854152,
      original_language: "ja",
      original_title: "犬部！",
      overview:
        "아오모리현 도와다시에 한 괴짜가 있었다. 하나이 소타, 22세 수의대생이다. 집에는 보호 동물이 빼곡하며 눈앞의 생명을 구하겠다는 생각으로 보호 활동을 하고 있다. 어느 날 소타는 한 실험견을 구하면서, 동기들과 동물 보호 활동 동아리인 '이누부'를 설립한다. 그로부터 16년 후. 수의사가 된 소타의 체포 소식을 듣고 개업의로서, 연구자로서, 유기동물센터 소장으로서 각각의 추억으로 부원들이 한 자리에 모이게 된다.",
      popularity: 2.597,
      poster_path: "/ogM5BcsZ6mboPcMonk8rLDi781r.jpg",
      release_date: "2023-10-16",
      title: "이누부!",
      video: false,
      vote_average: 3,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/vUcZcamOutBq1IUrsMtIw8Dkn6U.jpg",
      genre_ids: [99, 10402],
      id: 1165663,
      original_language: "ko",
      original_title: "서태지 25주년 라이브 타임: 트래블러",
      overview:
        "2017년 잠실 올림픽 주경기장에서 열린 데뷔 25주년 기념 콘서트 실황의 최초 극장 상영! 잊지 못할 레전드 공연 “ 서태지 25주년 콘서트”를 극장에서 만나다! 국내 최대 규모의 공연장인 잠실 올림픽 주경기장에서 약 3만 5천여명의 관객과 함께한 25주년 공연은 지난 25년간 선보인 그의 실험적인 음악과 완성도 높은 공연들을 집대성한 공연으로 대표된다. 특히 K-pop의 위상을 높이고 있는 그룹 방탄소년단이 특별 게스트로 참여해 공연의 의미를 더 했다. 서태지의 탄생을 알리는 ‘난 알아요’부터 ‘하여가’,‘ 환상속의 그대‘ 그리고 ’컴백홈' 까지! 서태지의 모든 히트곡과 명곡들을 오리지널 사운드 그대로 만날 수 있는 시간! 공연 실황 뿐 아니라 비하인드 장면까지 가슴 뜨거운 우리들만의 추억으로 만든 기념비적인 축제의 현장!",
      popularity: 1.508,
      poster_path: "/yugo5QIjhTRK6XQYQVOv4YnlJvZ.jpg",
      release_date: "2023-09-06",
      title: "서태지 25주년 라이브 타임: 트래블러",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/5WhkuNjWn8myCQ8Nnfw6XPwnisp.jpg",
      genre_ids: [28, 35],
      id: 987503,
      original_language: "ko",
      original_title: "잔고: 분노의 적자",
      overview:
        "가난하지만 영화감독이 꿈인 잔고는 배우가 꿈인 동생 잔디와 자신의 꿈을 위해 택배를 하며 열심히 살아간다. 끼니까지 거르며 열심히 영화 만들 돈을 모은 잔고 그러나 유명 연예 기획사에 들어갈 수 있는 기회가 생긴 절실한 동생 잔디를 위해서 전 재산을 내어준다. 그럼에도 불구하고 보내야 하는 돈은 계속해서 늘어나고 잔고의 잔고는 적자가 되고 만다. 결국 큰 빚을 지고 노예로 전락해 어디론가 끌려가는 잔고. 그리고 그의 앞에 무자비한 현상금 사냥꾼 닥터 솔트가 나타나며 잔고는 각성한다. 그렇게 분노의 적자, 잔고의 모험이 시작된다.",
      popularity: 2.111,
      poster_path: "/hlRHax3oqwQelp9KQ2HFig0o7cU.jpg",
      release_date: "2023-09-13",
      title: "잔고: 분노의 적자",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/iiXXsRTuoljS0SJOQml6jhImaSq.jpg",
      genre_ids: [18],
      id: 636362,
      original_language: "ko",
      original_title: "경미의 세계",
      overview:
        "7년 전, 가족과 연락을 끊고 서울로 올라온 배우 지망생 수연은 작은 극단에서 단역과 잡일을 하며 근근이 생활하고 있다. 그러던 어느 날, 수연은 통영에서 걸려 온 한 통의 전화를 받고 그곳으로 내려간다.",
      popularity: 1.928,
      poster_path: "/49B8rJzwmgeTBkwZaOJiba6vlFB.jpg",
      release_date: "2023-09-20",
      title: "경미의 세계",
      video: false,
      vote_average: 5.5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/i12K4LKnzrXV4Q8s64kYM25PMnY.jpg",
      genre_ids: [99],
      id: 913824,
      original_language: "en",
      original_title: "Free Chol Soo Lee",
      overview:
        "탕! 탕! 탕! 1973년 6월 3일, 미국 샌프란시스코 차이나타운 거리 한복판에서 중국인 갱단이 총격을 받고 사망한다. 5일 후, 한 동양인 청년이 살인 용의자로 긴급 체포된다. 이름 ‘철수 리’, 21살의 한인 이민자였다. 동양인 외모를 구별 못하는 백인 목격자들의 증언으로 종신형을 선고받은 이철수는 곧장 캘리포니아에서 가장 폭력적인 교도소에 수감된다. 그대로 묻힐 뻔했던 사건은 한 기자의 심층 보도로 다시 수면 위로 떠오른다. 한인 최초의 미국 주류 신문사 기자였던 이경원은 차이나타운 취재 중 우연히 이철수 사건을 접하고, 엉터리 재판 과정을 폭로한다. 이철수의 억울한 사연이 알려지며 한인 이민 사회와 종교계가 들끓고, 재심을 요구하는 구명 운동이 시작된다. ‘프리 철수 리’ 운동이 아시안아메리칸 사회를 뒤흔들며 빠르게 번져가던 중, 교도소 안 이철수는 갱의 공격으로부터 자신을 지키려다 진짜 살인을 저지르게 되는데…. 반전에 반전을 거듭한 10년의 재판, 그리고 아무도 예상하지 못했던 이철수의 나머지 삶의 반전! 2023년, 모두의 기대를 배반하고 충격적인 감동을 선사할, 당신의 인생 영화가 될 최고의 다큐멘터리!",
      popularity: 1.737,
      poster_path: "/40IwTtEOYDCMLXKuC4ronJJwJFm.jpg",
      release_date: "2023-10-18",
      title: "프리 철수 리",
      video: false,
      vote_average: 7.3,
      vote_count: 8,
    },
    {
      adult: false,
      backdrop_path: "/dFb79dk5W3wezcg7pxm49557b5g.jpg",
      genre_ids: [16, 35, 14, 9648],
      id: 952083,
      original_language: "ja",
      original_title: "映画おしりたんてい シリアーティ",
      overview:
        "호호 박물관 지하, 수수께끼로 둘러싸인 보물 ‘오파츠’를 노리는 세기의 악당 ‘시리어티’ 교수가 나타났다! 그를 막기 위해 ‘엉덩이 탐정’은 국제 경찰 원터폴 소속 ‘오드리’와 합동 수사를 펼치는데… “어둠으로 빛을 몰아 내주지. 이 ‘오파츠’의 힘으로 말이야” 세계를 뒤흔들 거대한 음모를 꾸미는 ‘시리어티’ 교수와 ‘엉덩이 탐정’의역대급 대결!",
      popularity: 1.882,
      poster_path: "/5V4fDz92fDzSB7MKvukavBT1OW2.jpg",
      release_date: "2023-09-28",
      title: "극장판 엉덩이 탐정: 미스터리 가면 ~최강의 대결",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/3xo1TDWQXL3AYpuDeruQ6UsR5Jv.jpg",
      genre_ids: [18, 53],
      id: 1000569,
      original_language: "nl",
      original_title: "The Chapel",
      overview:
        "어릴 적부터 피아노 영재로 불려온 ‘제니퍼’는 ‘퀸 엘리자베스 콩쿠르’ 우승으로 재능을 증명해야만 한다. 그는 결선에 오른 11명의 경쟁자와 함께 ‘뮤직 샤펠’이라 불리는 성에 갇혀 1주일의 연습 기간을 갖는다. 하지만, 폐쇄적인 공간과 경쟁 상황 속에 끔찍한 트라우마까지 되살아나며 극심한 불안에 시달리는데… 완벽함을 향한 광기에 가까운 집착이 시작되고, 그 누구도 믿을 수 없는 가운데 결선 날이 다가온다!",
      popularity: 0.756,
      poster_path: "/4tKQriUThMa8tGbufWZgLtoSVpM.jpg",
      release_date: "2023-09-13",
      title: "뮤직 샤펠",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [878, 9648, 53],
      id: 1189760,
      original_language: "ko",
      original_title: "Don't Look Deeper",
      overview:
        "인간과 로봇, 그 경계가 사라졌다!  고등학생인 아이샤는 파티에서 남자친구와 크게 다투게 되고  자신이 로봇이라는 충격적인 사실을 알게 된다.  지금까지 인간이라고 생각했던 자신의 모든 것이  누군가의 손으로 만들어졌다는 사실에  하나뿐인 가족이라 생각했던 아빠도,  믿고 의지했던 선생님도 더 이상 믿을 수 없게 되고 스스로를 의심하게 된다.  진짜 나는 무엇이고, 어디에서 왔는지 정체성 혼란을 겪는 가운데,\r 그녀는 리셋 되었던 과거를 알게 되고 엄청난 비밀을 알게 되는데…",
      popularity: 1.441,
      poster_path: "/cAZKPgBqvRxMdARbgwc2uqrzNny.jpg",
      release_date: "2023-09-07",
      title: "돈 룩 디퍼",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/sGLJm0lZdOjkZjezUuCJAVKw13n.jpg",
      genre_ids: [99],
      id: 637240,
      original_language: "ja",
      original_title: "つつんで、ひらいて",
      overview:
        "일본 출판계의 존경받는 북 디자이너 기쿠치 노부요시. 직접 종이를 자르고, 붙이고, 구겼다 펴는 등 수작업을 통해 평생 15,000권에 달하는 책 표지를 제작했다. 그의 작업 방식과 책을 대하는 태도는 가히 예술이라 말할 수 있지만, 그의 생각은 조금 다르다. 아버지가 책 디자이너였던 히로세 나나코 감독의 시선을 따라 기쿠치 노부요시의 장인 정신을 들여다본다.",
      popularity: 0.701,
      poster_path: "/oL1Hlrd7uT0r6IBRZHP7i5ddiEm.jpg",
      release_date: "2023-09-13",
      title: "책 종이 가위",
      video: false,
      vote_average: 5.5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/6LqMCQrpCnWHPx6jRmkRvIOiQOh.jpg",
      genre_ids: [18],
      id: 884759,
      original_language: "ko",
      original_title: "안녕, 내일 또 만나",
      overview:
        "열일곱 살 동준의 유일한 친구 강현이 높은 곳에서 떨어지던 날 밤, 동준은 이후 자기 인생의 방향을 결정시킬 만한 선택을 하게 된다. 그러한 선택에 대한 동준의 후회와 회한은, (그로 하여금) 결국 세 가지 다른 우주에서, 서로 다른 자신으로 사는 것에 대한 경험을 하게 만든다. 그것은 그로부터 이십여 년이 지난 현재의 서울과 대구, 부산에서 각기 다른 삶을 사는 마흔 두 살 동준(들)의 여러 인생들이다.",
      popularity: 1.015,
      poster_path: "/b9otFBI0oSlJ8dzdhpMxfnonWwG.jpg",
      release_date: "2023-09-13",
      title: "안녕, 내일 또 만나",
      video: false,
      vote_average: 5,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/ycrENJae8E9siHoplVONQrkIZJy.jpg",
      genre_ids: [99],
      id: 895179,
      original_language: "ko",
      original_title: "듣보인간의 생존신고",
      overview:
        "음악 오디션 프로그램  최종 우승자이자 ‘장르가 30호’라는 수식어로 불리며 일약 스타가 된 이승윤이 유명인이 되기 직전, 우린 ‘무명’이었던 그를 찾아갔었다. 2년 전 우연한 기회로 그의 노래를 듣곤 2년 뒤 무작정 찾아가 뮤직비디오를 찍어 주겠다고 한다. 뮤직비디오는 한 번도 찍어 본 적 없는 무명인들의 어처구니없는 제안을 시작으로 우리들의 이름을 되찾기 위한 여정이 시작된다.",
      popularity: 1.176,
      poster_path: "/ugi8wJb23F59s5rJe52cegKbclG.jpg",
      release_date: "2023-09-06",
      title: "듣보인간의 생존신고",
      video: false,
      vote_average: 6,
      vote_count: 2,
    },
  ],
  total_pages: 5,
  total_results: 96,
};

export default nowplaying;